module.exports = [
{rejestr: 'ster_temp', adres: 16389, nazwa : 'Delta', nazwa_zm : 'MB_NAST_1_Delta', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 18},
{rejestr: 'ster_temp', adres: 16391, nazwa : 'eko', nazwa_zm : 'MB_NAST_2_eko', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 18},
{rejestr: 'ster_temp', adres: 16393, nazwa : 'Gabinet_dol', nazwa_zm : 'MB_NAST_3_Gabinet_dol', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 3},
{rejestr: 'ster_temp', adres: 16395, nazwa : 'WC', nazwa_zm : 'MB_NAST_4_WC_dol', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 4},
{rejestr: 'ster_temp', adres: 16397, nazwa : 'Salon', nazwa_zm : 'MB_NAST_5_Salon', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 1},
{rejestr: 'ster_temp', adres: 16399, nazwa : 'Pokoj_Macka', nazwa_zm : 'MB_NAST_6_Pokoj_Macka', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 11},
{rejestr: 'ster_temp', adres: 16401, nazwa : 'Gabinet_gora', nazwa_zm : 'MB_NAST_7_Gabinet_gora', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 10},
{rejestr: 'ster_temp', adres: 16403, nazwa : 'Lazienka', nazwa_zm : 'MB_NAST_8_WC_gora', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 13},
{rejestr: 'ster_temp', adres: 16405, nazwa : 'Sypialnia', nazwa_zm : 'MB_NAST_9_Sypialnia', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 9},
{rejestr: 'ster_temp', adres: 16407, nazwa : 'Pok_goscinny', nazwa_zm : 'MB_NAST_10_Pok_goscinny', ster_wy : 'ster', rodzaj : 'temp_nast', lok_id : 12},
{rejestr: 'sterowania', adres: 16500, nazwa : 'puste', nazwa_zm : 'MB_STER_0', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 18},
{rejestr: 'sterowania', adres: 16501, nazwa : 'Sufit', nazwa_zm : 'MB_STER_1_OSW_Gabinet_dol_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 3},
{rejestr: 'sterowania', adres: 16502, nazwa : 'puste', nazwa_zm : 'MB_STER_2_OSW_Gabinet_dol_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 18},
{rejestr: 'sterowania', adres: 16503, nazwa : 'Sufit', nazwa_zm : 'MB_STER_3_OSW_Wiatrolap', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 5},
{rejestr: 'sterowania', adres: 16504, nazwa : 'Sufit', nazwa_zm : 'MB_STER_4_OSW_Korytarz_dol', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 6},
{rejestr: 'sterowania', adres: 16505, nazwa : 'barek', nazwa_zm : 'MB_STER_5_OSW_Kuchnia_barek', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'sterowania', adres: 16506, nazwa : 'sufit', nazwa_zm : 'MB_STER_6_OSW_Kuchnia_gk', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'sterowania', adres: 16507, nazwa : 'sufit led', nazwa_zm : 'MB_STER_7_OSW_Kuchnia_ledy_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'sterowania', adres: 16508, nazwa : 'Zyrandor gora', nazwa_zm : 'MB_STER_8_OSW_Jadalnia_zyralnd_gora', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'sterowania', adres: 16509, nazwa : 'Taras_od_ogrodu', nazwa_zm : 'MB_STER_9_OSW_Taras_od_ogrodu', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16510, nazwa : 'Taras_od_strony_Raf', nazwa_zm : 'MB_STER_10_OSW_Taras_od_strony_Raf', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16511, nazwa : 'Jadalnia kinkiet', nazwa_zm : 'MB_STER_11_OSW_Jadalnia_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'sterowania', adres: 16512, nazwa : 'Kinkiet słup', nazwa_zm : 'MB_STER_12_OSW_Salon_kinkiet_slup', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'sterowania', adres: 16513, nazwa : 'Zyrandor dol', nazwa_zm : 'MB_STER_13_OSW_Jadalnia_zyrand_dol', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'sterowania', adres: 16514, nazwa : 'Sufit', nazwa_zm : 'MB_STER_14_OSW_Lazienka_dol', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 4},
{rejestr: 'sterowania', adres: 16515, nazwa : 'Sufit', nazwa_zm : 'MB_STER_15_OSW_Schody_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 16},
{rejestr: 'sterowania', adres: 16516, nazwa : 'Balkon pok Radka', nazwa_zm : 'MB_STER_16_OSW_Gabine_gora_balkon', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'sterowania', adres: 16517, nazwa : 'Sufit', nazwa_zm : 'MB_STER_17_OSW_Gabine_gora_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'sterowania', adres: 16518, nazwa : 'Kinkiet', nazwa_zm : 'MB_STER_18_OSW_Gabinet_gora_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'sterowania', adres: 16519, nazwa : 'Sufit', nazwa_zm : 'MB_STER_19_OSW_Sypialnia_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'sterowania', adres: 16520, nazwa : 'Kinkiet', nazwa_zm : 'MB_STER_20_OSW_Sypialnia_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'sterowania', adres: 16521, nazwa : 'Sufit_lustro', nazwa_zm : 'MB_STER_21_OSW_Lazienka_gora_lustro_gk', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 13},
{rejestr: 'sterowania', adres: 16522, nazwa : 'Sufit_wanna', nazwa_zm : 'MB_STER_22_OSW_Lazienka_gora_wanna_gk', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 13},
{rejestr: 'sterowania', adres: 16523, nazwa : 'Sufit', nazwa_zm : 'MB_STER_23_OSW_Pokoj_gora_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 11},
{rejestr: 'sterowania', adres: 16524, nazwa : 'Kinkiet', nazwa_zm : 'MB_STER_24_OSW_Pokoj_gora_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 11},
{rejestr: 'sterowania', adres: 16525, nazwa : 'Stopnie', nazwa_zm : 'MB_STER_25_OSW_Schody_stopnie', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 16},
{rejestr: 'sterowania', adres: 16526, nazwa : 'Nad garażem', nazwa_zm : 'MB_STER_26_OSW_Zewn_garaz', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16527, nazwa : 'Przed wejsciem', nazwa_zm : 'MB_STER_27_OSW_Zewn_wejscie', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16528, nazwa : 'Taras przy sypialni', nazwa_zm : 'MB_STER_28_OSW_Sypialnia_taras', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'sterowania', adres: 16529, nazwa : 'Sufit', nazwa_zm : 'MB_STER_29_OSW_Pokoj_goscinny', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 12},
{rejestr: 'sterowania', adres: 16530, nazwa : 'Sufit', nazwa_zm : 'MB_STER_30_OSW_Garaz_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 7},
{rejestr: 'sterowania', adres: 16531, nazwa : 'puste', nazwa_zm : 'MB_STER_31_OSW_Rezerwa2', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 18},
{rejestr: 'sterowania', adres: 16532, nazwa : 'Sufit_szafa', nazwa_zm : 'MB_STER_32_OSW_Korytarz_gora_szafa', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 14},
{rejestr: 'sterowania', adres: 16533, nazwa : 'Sufit', nazwa_zm : 'MB_STER_33_OSW_Korytarz_gora_sufit', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 14},
{rejestr: 'sterowania', adres: 16534, nazwa : 'Podbitka_przod_boki', nazwa_zm : 'MB_STER_34_OSW_Podbitka_przod_boki', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16535, nazwa : 'Podbitka_tyl', nazwa_zm : 'MB_STER_35_OSW_Podbitka_tyl', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'sterowania', adres: 16536, nazwa : 'Nad ekranem', nazwa_zm : 'MB_STER_36_OSW_Salon_ekran', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'sterowania', adres: 16537, nazwa : 'Kinkiet', nazwa_zm : 'MB_STER_37_OSW_Garaz_kinkiet', ster_wy : 'ster', rodzaj : 'swiatlo', lok_id : 7},
{rejestr: 'sterowania', adres: 16538, nazwa : 'zal_wyl', nazwa_zm : 'MB_STER_38_Brink_zal_wyl', ster_wy : 'ster', rodzaj : 'brink', lok_id : 18},
{rejestr: 'sterowania', adres: 16539, nazwa : '2bieg', nazwa_zm : 'MB_STER_39_Brink_2bieg', ster_wy : 'ster', rodzaj : 'brink', lok_id : 18},
{rejestr: 'sterowania', adres: 16540, nazwa : '3bieg', nazwa_zm : 'MB_STER_40_Brink_3bieg', ster_wy : 'ster', rodzaj : 'brink', lok_id : 18},
{rejestr: 'sterowania', adres: 16541, nazwa : 'Grzanie_WC', nazwa_zm : 'MB_STER_41_Grzanie_WC_dol', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 4},
{rejestr: 'sterowania', adres: 16542, nazwa : 'Grzanie_salon', nazwa_zm : 'MB_STER_42_Grzanie_salon', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 1},
{rejestr: 'sterowania', adres: 16543, nazwa : 'Grzanie_salon_kanal', nazwa_zm : 'MB_STER_43_Grzanie_salon_kanal', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 1},
{rejestr: 'sterowania', adres: 16544, nazwa : 'Grzanie_gabinet_dol', nazwa_zm : 'MB_STER_44_Grzanie_gabinet_dol', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 3},
{rejestr: 'sterowania', adres: 16545, nazwa : 'Grzanie_kotlownia', nazwa_zm : 'MB_STER_45_Grzanie_kotlownia', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 8},
{rejestr: 'sterowania', adres: 16546, nazwa : 'Grzanie_pokoj_Macka', nazwa_zm : 'MB_STER_46_Grzanie_pokoj_Macka', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 11},
{rejestr: 'sterowania', adres: 16547, nazwa : 'Grzanie_gabinet_gora', nazwa_zm : 'MB_STER_47_Grzanie_gabinet_gora', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 10},
{rejestr: 'sterowania', adres: 16548, nazwa : 'Grzanie_lazienka', nazwa_zm : 'MB_STER_48_Grzanie_wc_gora', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 13},
{rejestr: 'sterowania', adres: 16549, nazwa : 'Grzanie_sypialnia', nazwa_zm : 'MB_STER_49_Grzanie_sypialnia', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 9},
{rejestr: 'sterowania', adres: 16550, nazwa : 'Grzanie_pok_gosc', nazwa_zm : 'MB_STER_50_Grzanie_poddasze', ster_wy : 'ster', rodzaj : 'ogrzew', lok_id : 12},
{rejestr: 'sterowania', adres: 16551, nazwa : 'puste', nazwa_zm : 'MB_STER_51_rezerwa', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16552, nazwa : 'puste', nazwa_zm : 'MB_STER_52_rezerwa', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16553, nazwa : 'Gniazdo zewn', nazwa_zm : 'MB_STER_53_Sila_gniazdo_zewnetrzne', ster_wy : 'ster', rodzaj : 'sila', lok_id : 17},
{rejestr: 'sterowania', adres: 16554, nazwa : 'Taras gniazdo', nazwa_zm : 'MB_STER_54_Sila_gniazdo_taras_dol', ster_wy : 'ster', rodzaj : 'sila', lok_id : 17},
{rejestr: 'sterowania', adres: 16555, nazwa : 'Sila_poddasze_tv', nazwa_zm : 'MB_STER_55_Sila_poddasze_tv', ster_wy : 'ster', rodzaj : 'sila', lok_id : 12},
{rejestr: 'sterowania', adres: 16556, nazwa : 'Sila_sypialnia_tv', nazwa_zm : 'MB_STER_56_Sila_sypialnia_tv', ster_wy : 'ster', rodzaj : 'sila', lok_id : 9},
{rejestr: 'sterowania', adres: 16557, nazwa : 'Sila_gabinet_gora', nazwa_zm : 'MB_STER_57_Sila_gabinet_gora', ster_wy : 'ster', rodzaj : 'sila', lok_id : 10},
{rejestr: 'sterowania', adres: 16558, nazwa : 'Balkon sypialni', nazwa_zm : 'MB_STER_58_Sila_zewnetrzne_sypialni', ster_wy : 'ster', rodzaj : 'sila', lok_id : 17},
{rejestr: 'sterowania', adres: 16559, nazwa : 'puste', nazwa_zm : 'MB_STER_59_rezerwa', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16560, nazwa : 'puste', nazwa_zm : 'MB_STER_60_rezerwa', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16561, nazwa : 'ekran_g', nazwa_zm : 'MB_STER_61_Ekran_G', ster_wy : 'ster', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'sterowania', adres: 16562, nazwa : 'ekran_d', nazwa_zm : 'MB_STER_62_Ekran_D', ster_wy : 'ster', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'sterowania', adres: 16563, nazwa : 'puste', nazwa_zm : 'MB_STER_63_Roleta1_G', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16564, nazwa : 'puste', nazwa_zm : 'MB_STER_64_Roleta1_D', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16565, nazwa : 'puste', nazwa_zm : 'MB_STER_65', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16566, nazwa : 'puste', nazwa_zm : 'MB_STER_66', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16567, nazwa : 'puste', nazwa_zm : 'MB_STER_67', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16568, nazwa : 'puste', nazwa_zm : 'MB_STER_68', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16569, nazwa : 'puste', nazwa_zm : 'MB_STER_69', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16570, nazwa : 'puste', nazwa_zm : 'MB_STER_70', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16571, nazwa : 'puste', nazwa_zm : 'MB_STER_71', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16572, nazwa : 'puste', nazwa_zm : 'MB_STER_72', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16573, nazwa : 'puste', nazwa_zm : 'MB_STER_73', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16574, nazwa : 'puste', nazwa_zm : 'MB_STER_74', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16575, nazwa : 'puste', nazwa_zm : 'MB_STER_75', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16576, nazwa : 'puste', nazwa_zm : 'MB_STER_76', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16577, nazwa : 'puste', nazwa_zm : 'MB_STER_77', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16578, nazwa : 'puste', nazwa_zm : 'MB_STER_78', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16579, nazwa : 'puste', nazwa_zm : 'MB_STER_79', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16580, nazwa : 'puste', nazwa_zm : 'MB_STER_80', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16581, nazwa : 'puste', nazwa_zm : 'MB_STER_81', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16582, nazwa : 'puste', nazwa_zm : 'MB_STER_82', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16583, nazwa : 'puste', nazwa_zm : 'MB_STER_83', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16584, nazwa : 'puste', nazwa_zm : 'MB_STER_84', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16585, nazwa : 'puste', nazwa_zm : 'MB_STER_85', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16586, nazwa : 'puste', nazwa_zm : 'MB_STER_86', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16587, nazwa : 'puste', nazwa_zm : 'MB_STER_87', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16588, nazwa : 'puste', nazwa_zm : 'MB_STER_88', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16589, nazwa : 'puste', nazwa_zm : 'MB_STER_89', ster_wy : 'ster', rodzaj : 'puste', lok_id : 18},
{rejestr: 'sterowania', adres: 16590, nazwa : 'ekran_poz', nazwa_zm : 'MB_STER_90_Ekran_Pozycja', ster_wy : 'ster', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'wyjscia', adres: 16901, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_1_OSW_Gabinet_dol_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 3},
{rejestr: 'wyjscia', adres: 16902, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_2_OSW_Gabinet_dol_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 18},
{rejestr: 'wyjscia', adres: 16903, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_3_OSW_Wiatrolap', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 5},
{rejestr: 'wyjscia', adres: 16904, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_4_OSW_Korytarz_dol', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 6},
{rejestr: 'wyjscia', adres: 16905, nazwa : 'barek', nazwa_zm : 'MB_WYJSCIA_5_OSW_Kuchnia_barek', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'wyjscia', adres: 16906, nazwa : 'sufit', nazwa_zm : 'MB_WYJSCIA_6_OSW_Kuchnia_gk', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'wyjscia', adres: 16907, nazwa : 'sufit led', nazwa_zm : 'MB_WYJSCIA_7_OSW_Kuchnia_ledy_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 2},
{rejestr: 'wyjscia', adres: 16908, nazwa : 'Zyrandor gora', nazwa_zm : 'MB_WYJSCIA_8_OSW_Jadalnia_zyralnd_gora', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'wyjscia', adres: 16909, nazwa : 'Taras_od_ogrodu', nazwa_zm : 'MB_WYJSCIA_9_OSW_Taras_od_ogrodu', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16910, nazwa : 'Taras_od_strony_Raf', nazwa_zm : 'MB_WYJSCIA_10_OSW_Taras_od_strony_Raf', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16911, nazwa : 'Jadalnia kinkiet', nazwa_zm : 'MB_WYJSCIA_11_OSW_Jadalnia_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'wyjscia', adres: 16912, nazwa : 'Kinkiet słup', nazwa_zm : 'MB_WYJSCIA_12_OSW_Salon_kinkiet_slup', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'wyjscia', adres: 16913, nazwa : 'Zyrandor dol', nazwa_zm : 'MB_WYJSCIA_13_OSW_Jadalnia_zyrand_dol', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'wyjscia', adres: 16914, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_14_OSW_Lazienka_dol', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 4},
{rejestr: 'wyjscia', adres: 16915, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_15_OSW_Schody_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 16},
{rejestr: 'wyjscia', adres: 16916, nazwa : 'Balkon pok Radka', nazwa_zm : 'MB_WYJSCIA_16_OSW_Gabine_gora_balkon', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'wyjscia', adres: 16917, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_17_OSW_Gabine_gora_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'wyjscia', adres: 16918, nazwa : 'Kinkiet', nazwa_zm : 'MB_WYJSCIA_18_OSW_Gabinet_gora_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 10},
{rejestr: 'wyjscia', adres: 16919, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_19_OSW_Sypialnia_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'wyjscia', adres: 16920, nazwa : 'Kinkiet', nazwa_zm : 'MB_WYJSCIA_20_OSW_Sypialnia_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'wyjscia', adres: 16921, nazwa : 'Sufit_lustro', nazwa_zm : 'MB_WYJSCIA_21_OSW_Lazienka_gora_lustro_gk', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 13},
{rejestr: 'wyjscia', adres: 16922, nazwa : 'Sufit_wanna', nazwa_zm : 'MB_WYJSCIA_22_OSW_Lazienka_gora_wanna_gk', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 13},
{rejestr: 'wyjscia', adres: 16923, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_23_OSW_Pokoj_gora_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 11},
{rejestr: 'wyjscia', adres: 16924, nazwa : 'Kinkiet', nazwa_zm : 'MB_WYJSCIA_24_OSW_Pokoj_gora_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 11},
{rejestr: 'wyjscia', adres: 16925, nazwa : 'Stopnie', nazwa_zm : 'MB_WYJSCIA_25_OSW_Schody_stopnie', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 16},
{rejestr: 'wyjscia', adres: 16926, nazwa : 'Nad garażem', nazwa_zm : 'MB_WYJSCIA_26_OSW_Zewn_garaz', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16927, nazwa : 'Przed wejsciem', nazwa_zm : 'MB_WYJSCIA_27_OSW_Zewn_wejscie', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16928, nazwa : 'Taras przy sypialni', nazwa_zm : 'MB_WYJSCIA_28_OSW_Sypialnia_taras', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 9},
{rejestr: 'wyjscia', adres: 16929, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_29_OSW_Pokoj_goscinny', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 12},
{rejestr: 'wyjscia', adres: 16930, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_30_OSW_Garaz_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 7},
{rejestr: 'wyjscia', adres: 16931, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_31_OSW_Rezerwa2', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 18},
{rejestr: 'wyjscia', adres: 16932, nazwa : 'Sufit_szafa', nazwa_zm : 'MB_WYJSCIA_32_OSW_Korytarz_gora_szafa', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 14},
{rejestr: 'wyjscia', adres: 16933, nazwa : 'Sufit', nazwa_zm : 'MB_WYJSCIA_33_OSW_Korytarz_gora_sufit', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 14},
{rejestr: 'wyjscia', adres: 16934, nazwa : 'Podbitka_przod_boki', nazwa_zm : 'MB_WYJSCIA_34_OSW_Podbitka_przod_boki', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16935, nazwa : 'Podbitka_tyl', nazwa_zm : 'MB_WYJSCIA_35_OSW_Podbitka_tyl', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 17},
{rejestr: 'wyjscia', adres: 16936, nazwa : 'Nad ekranem', nazwa_zm : 'MB_WYJSCIA_36_OSW_Salon_ekran', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 1},
{rejestr: 'wyjscia', adres: 16937, nazwa : 'Kinkiet', nazwa_zm : 'MB_WYJSCIA_37_OSW_Garaz_kinkiet', ster_wy : 'wy', rodzaj : 'swiatlo', lok_id : 7},
{rejestr: 'wyjscia', adres: 16938, nazwa : 'zal_wyl', nazwa_zm : 'MB_WYJSCIA_38_Brink_zal_wyl', ster_wy : 'wy', rodzaj : 'brink', lok_id : 18},
{rejestr: 'wyjscia', adres: 16939, nazwa : '2bieg', nazwa_zm : 'MB_WYJSCIA_39_Brink_2bieg', ster_wy : 'wy', rodzaj : 'brink', lok_id : 18},
{rejestr: 'wyjscia', adres: 16940, nazwa : '3bieg', nazwa_zm : 'MB_WYJSCIA_40_Brink_3bieg', ster_wy : 'wy', rodzaj : 'brink', lok_id : 18},
{rejestr: 'wyjscia', adres: 16941, nazwa : 'Grzanie_WC', nazwa_zm : 'MB_WYJSCIA_41_Grzanie_WC_dol', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 4},
{rejestr: 'wyjscia', adres: 16942, nazwa : 'Grzanie_salon', nazwa_zm : 'MB_WYJSCIA_42_Grzanie_salon', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 1},
{rejestr: 'wyjscia', adres: 16943, nazwa : 'Grzanie_salon_kanal', nazwa_zm : 'MB_WYJSCIA_43_Grzanie_salon_kanal', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 1},
{rejestr: 'wyjscia', adres: 16944, nazwa : 'Grzanie_gabinet_dol', nazwa_zm : 'MB_WYJSCIA_44_Grzanie_gabinet_dol', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 3},
{rejestr: 'wyjscia', adres: 16945, nazwa : 'Grzanie_kotlownia', nazwa_zm : 'MB_WYJSCIA_45_Grzanie_kotlownia', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 8},
{rejestr: 'wyjscia', adres: 16946, nazwa : 'Grzanie_pokoj_Macka', nazwa_zm : 'MB_WYJSCIA_46_Grzanie_pokoj_Macka', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 11},
{rejestr: 'wyjscia', adres: 16947, nazwa : 'Grzanie_gabinet_gora', nazwa_zm : 'MB_WYJSCIA_47_Grzanie_gabinet_gora', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 10},
{rejestr: 'wyjscia', adres: 16948, nazwa : 'Grzanie_lazienka', nazwa_zm : 'MB_WYJSCIA_48_Grzanie_wc_gora', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 13},
{rejestr: 'wyjscia', adres: 16949, nazwa : 'Grzanie_sypialnia', nazwa_zm : 'MB_WYJSCIA_49_Grzanie_sypialnia', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 9},
{rejestr: 'wyjscia', adres: 16950, nazwa : 'Grzanie_pok_gosc', nazwa_zm : 'MB_WYJSCIA_50_Grzanie_poddasze', ster_wy : 'wy', rodzaj : 'ogrzew', lok_id : 12},
{rejestr: 'wyjscia', adres: 16951, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_51_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16952, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_52_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16953, nazwa : 'Gniazdo zewn', nazwa_zm : 'MB_WYJSCIA_53_Sila_gniazdo_zewnetrzne', ster_wy : 'wy', rodzaj : 'sila', lok_id : 17},
{rejestr: 'wyjscia', adres: 16954, nazwa : 'Taras gniazdo', nazwa_zm : 'MB_WYJSCIA_54_Sila_gniazdo_taras_dol', ster_wy : 'wy', rodzaj : 'sila', lok_id : 17},
{rejestr: 'wyjscia', adres: 16955, nazwa : 'Sila_poddasze_tv', nazwa_zm : 'MB_WYJSCIA_55_Sila_poddasze_tv', ster_wy : 'wy', rodzaj : 'sila', lok_id : 12},
{rejestr: 'wyjscia', adres: 16956, nazwa : 'Sila_sypialnia_tv', nazwa_zm : 'MB_WYJSCIA_56_Sila_sypialnia_tv', ster_wy : 'wy', rodzaj : 'sila', lok_id : 9},
{rejestr: 'wyjscia', adres: 16957, nazwa : 'Sila_gabinet_gora', nazwa_zm : 'MB_WYJSCIA_57_Sila_gabinet_gora', ster_wy : 'wy', rodzaj : 'sila', lok_id : 10},
{rejestr: 'wyjscia', adres: 16958, nazwa : 'Balkon sypialni', nazwa_zm : 'MB_WYJSCIA_58_Sila_zewnetrzne_sypialni', ster_wy : 'wy', rodzaj : 'sila', lok_id : 17},
{rejestr: 'wyjscia', adres: 16959, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_59_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16960, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_60_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16961, nazwa : 'ekran_g', nazwa_zm : 'MB_WYJSCIA_61_Ekran_G', ster_wy : 'wy', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'wyjscia', adres: 16962, nazwa : 'ekran_d', nazwa_zm : 'MB_WYJSCIA_62_Ekran_D', ster_wy : 'wy', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'wyjscia', adres: 16963, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_63_Roleta1_G', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16964, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_64_Roleta1_D', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16965, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_65', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16966, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_66', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16967, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_67', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16968, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_68', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16969, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_69', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16970, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_70', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16971, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_71', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16972, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_72', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16973, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_73', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16974, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_74', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16975, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_75', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16976, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_76', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16977, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_77', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16978, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_78', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16979, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_79', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16980, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_80', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16981, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_81', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16982, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_82', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16983, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_83', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16984, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_84', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16985, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_85', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16986, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_86', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16987, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_87', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16988, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_88', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16989, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_89', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16990, nazwa : 'ekran_poz', nazwa_zm : 'MB_WYJSCIA_90_Ekran_Pozycja', ster_wy : 'wy', rodzaj : 'ekran', lok_id : 1},
{rejestr: 'wyjscia', adres: 16991, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_91', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16992, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_92', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16993, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_93', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16994, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_94', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16995, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_95', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16996, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_96', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16997, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_97', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16998, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_98', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 16999, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_99', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wyjscia', adres: 17000, nazwa : 'puste', nazwa_zm : 'MB_WYJSCIA_100', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wy_satel', adres: 17100, nazwa : 'K_1', nazwa_zm : 'MB_SATEL_1_K_1', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17101, nazwa : 'K_Wyjscie_ogrod', nazwa_zm : 'MB_SATEL_2_K_Wyjscie_ogrod', ster_wy : 'wy', rodzaj : 'satel', lok_id : 17},
{rejestr: 'wy_satel', adres: 17102, nazwa : 'K_Okno_taras', nazwa_zm : 'MB_SATEL_3_K_Okno_taras', ster_wy : 'wy', rodzaj : 'satel', lok_id : 1},
{rejestr: 'wy_satel', adres: 17103, nazwa : 'K_Kuchnia', nazwa_zm : 'MB_SATEL_4_K_Kuchnia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 2},
{rejestr: 'wy_satel', adres: 17104, nazwa : 'K_5', nazwa_zm : 'MB_SATEL_5_K_5', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17105, nazwa : 'K_6', nazwa_zm : 'MB_SATEL_6_K_6', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17106, nazwa : 'K_Okno_klatka', nazwa_zm : 'MB_SATEL_7_K_Okno_klatka', ster_wy : 'wy', rodzaj : 'satel', lok_id : 16},
{rejestr: 'wy_satel', adres: 17107, nazwa : 'K_Sypialnia_taras', nazwa_zm : 'MB_SATEL_8_K_Sypialnia_taras', ster_wy : 'wy', rodzaj : 'satel', lok_id : 9},
{rejestr: 'wy_satel', adres: 17108, nazwa : 'K_Lazienka_gora', nazwa_zm : 'MB_SATEL_9_K_Lazienka_gora', ster_wy : 'wy', rodzaj : 'satel', lok_id : 13},
{rejestr: 'wy_satel', adres: 17109, nazwa : 'K_Okno_gabinet_gora', nazwa_zm : 'MB_SATEL_10_K_Okno_gabinet_gora', ster_wy : 'wy', rodzaj : 'satel', lok_id : 10},
{rejestr: 'wy_satel', adres: 17110, nazwa : 'K_Okno_pokoj_Macka', nazwa_zm : 'MB_SATEL_11_K_Okno_pokoj_Macka', ster_wy : 'wy', rodzaj : 'satel', lok_id : 11},
{rejestr: 'wy_satel', adres: 17111, nazwa : 'K_Okno_pralnia', nazwa_zm : 'MB_SATEL_12_K_Okno_pralnia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 15},
{rejestr: 'wy_satel', adres: 17112, nazwa : 'K_Okno_pokoj_goscinny', nazwa_zm : 'MB_SATEL_13_K_Okno_pokoj_goscinny', ster_wy : 'wy', rodzaj : 'satel', lok_id : 12},
{rejestr: 'wy_satel', adres: 17113, nazwa : 'K_14', nazwa_zm : 'MB_SATEL_14_K_14', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17114, nazwa : 'S_Syreny', nazwa_zm : 'MB_SATEL_15_S_Syreny', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17115, nazwa : 'S_Centrali', nazwa_zm : 'MB_SATEL_16_S_Centrali', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17116, nazwa : 'PIR_Garaz', nazwa_zm : 'MB_SATEL_17_PIR_Garaz', ster_wy : 'wy', rodzaj : 'satel', lok_id : 7},
{rejestr: 'wy_satel', adres: 17117, nazwa : 'PIR_Kotlownia', nazwa_zm : 'MB_SATEL_18_PIR_Kotlownia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 8},
{rejestr: 'wy_satel', adres: 17118, nazwa : 'PIR_Salon', nazwa_zm : 'MB_SATEL_19_PIR_Salon', ster_wy : 'wy', rodzaj : 'satel', lok_id : 1},
{rejestr: 'wy_satel', adres: 17119, nazwa : 'PIR_Kuchnia', nazwa_zm : 'MB_SATEL_20_PIR_Kuchnia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 2},
{rejestr: 'wy_satel', adres: 17120, nazwa : 'PIR_Korytarz_dol', nazwa_zm : 'MB_SATEL_21_PIR_Korytarz_dol', ster_wy : 'wy', rodzaj : 'satel', lok_id : 6},
{rejestr: 'wy_satel', adres: 17121, nazwa : 'PIR_Gabinet_dol', nazwa_zm : 'MB_SATEL_22_PIR_Gabinet_dol', ster_wy : 'wy', rodzaj : 'satel', lok_id : 3},
{rejestr: 'wy_satel', adres: 17122, nazwa : 'PIR_Wiatrolap', nazwa_zm : 'MB_SATEL_23_PIR_Wiatrolap', ster_wy : 'wy', rodzaj : 'satel', lok_id : 5},
{rejestr: 'wy_satel', adres: 17123, nazwa : 'PIR_Klatka_schodowa', nazwa_zm : 'MB_SATEL_24_PIR_Klatka_schodowa', ster_wy : 'wy', rodzaj : 'satel', lok_id : 16},
{rejestr: 'wy_satel', adres: 17124, nazwa : 'PIR_Korytarz_gora', nazwa_zm : 'MB_SATEL_25_PIR_Korytarz_gora', ster_wy : 'wy', rodzaj : 'satel', lok_id : 14},
{rejestr: 'wy_satel', adres: 17125, nazwa : 'PIR_Pralnia', nazwa_zm : 'MB_SATEL_26_PIR_Pralnia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 15},
{rejestr: 'wy_satel', adres: 17126, nazwa : 'PIR_Gabinet_gora', nazwa_zm : 'MB_SATEL_27_PIR_Gabinet_gora', ster_wy : 'wy', rodzaj : 'satel', lok_id : 10},
{rejestr: 'wy_satel', adres: 17127, nazwa : 'PIR_Pokoj_goscinny', nazwa_zm : 'MB_SATEL_28_PIR_Pokoj_goscinny', ster_wy : 'wy', rodzaj : 'satel', lok_id : 12},
{rejestr: 'wy_satel', adres: 17128, nazwa : 'PIR_Pokoj_Macka', nazwa_zm : 'MB_SATEL_29_PIR_Pokoj_Macka', ster_wy : 'wy', rodzaj : 'satel', lok_id : 11},
{rejestr: 'wy_satel', adres: 17129, nazwa : 'PIR_Sypialnia', nazwa_zm : 'MB_SATEL_30_PIR_Sypialnia', ster_wy : 'wy', rodzaj : 'satel', lok_id : 9},
{rejestr: 'wy_satel', adres: 17130, nazwa : 'PIR', nazwa_zm : 'MB_SATEL_31_PIR', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17131, nazwa : 'PIR', nazwa_zm : 'MB_SATEL_32_PIR', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17132, nazwa : 'PIR', nazwa_zm : 'MB_SATEL_33_PIR', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17133, nazwa : 'PIR', nazwa_zm : 'MB_SATEL_34_PIR', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17134, nazwa : 'A_Gaz', nazwa_zm : 'MB_SATEL_35_A_Gaz', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17135, nazwa : 'A_Dym', nazwa_zm : 'MB_SATEL_36_A_Dym', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17136, nazwa : 'K_Wejscie_glowne', nazwa_zm : 'MB_SATEL_37_K_Wejscie_glowne', ster_wy : 'wy', rodzaj : 'satel', lok_id : 18},
{rejestr: 'wy_satel', adres: 17137, nazwa : 'rezerwa', nazwa_zm : 'MB_SATEL_38_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wy_satel', adres: 17138, nazwa : 'rezerwa', nazwa_zm : 'MB_SATEL_39_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wy_satel', adres: 17139, nazwa : 'rezerwa', nazwa_zm : 'MB_SATEL_40_rezerwa', ster_wy : 'wy', rodzaj : 'puste', lok_id : 18},
{rejestr: 'wy_temp', adres: 17197, nazwa : 'Garaz', nazwa_zm : 'MB_TEMP_1_Garaz', ster_wy : 'wy', rodzaj : 'temp', lok_id : 7},
{rejestr: 'wy_temp', adres: 17199, nazwa : 'Wiatrolap', nazwa_zm : 'MB_TEMP_2_Wiatrolap', ster_wy : 'wy', rodzaj : 'temp', lok_id : 5},
{rejestr: 'wy_temp', adres: 17201, nazwa : 'Gabinet_dol', nazwa_zm : 'MB_TEMP_3_Gabinet_dol', ster_wy : 'wy', rodzaj : 'temp', lok_id : 3},
{rejestr: 'wy_temp', adres: 17203, nazwa : 'Salon', nazwa_zm : 'MB_TEMP_4_Salon_slup', ster_wy : 'wy', rodzaj : 'temp', lok_id : 1},
{rejestr: 'wy_temp', adres: 17205, nazwa : 'WC', nazwa_zm : 'MB_TEMP_5_Lazienka_dol', ster_wy : 'wy', rodzaj : 'temp', lok_id : 4},
{rejestr: 'wy_temp', adres: 17207, nazwa : 'Korytarz_gora', nazwa_zm : 'MB_TEMP_6_Korytarz_gora(przyschodach)', ster_wy : 'wy', rodzaj : 'temp', lok_id : 14},
{rejestr: 'wy_temp', adres: 17209, nazwa : 'Sypialnia', nazwa_zm : 'MB_TEMP_7_Sypialnia', ster_wy : 'wy', rodzaj : 'temp', lok_id : 9},
{rejestr: 'wy_temp', adres: 17211, nazwa : 'Lazienka', nazwa_zm : 'MB_TEMP_8_Lazienka_gora', ster_wy : 'wy', rodzaj : 'temp', lok_id : 13},
{rejestr: 'wy_temp', adres: 17213, nazwa : 'Gabinet_gora', nazwa_zm : 'MB_TEMP_9_Gabinet_gora', ster_wy : 'wy', rodzaj : 'temp', lok_id : 10},
{rejestr: 'wy_temp', adres: 17215, nazwa : 'Pokoj_Macka', nazwa_zm : 'MB_TEMP_10_Pokoj_Macka', ster_wy : 'wy', rodzaj : 'temp', lok_id : 11},
{rejestr: 'wy_temp', adres: 17217, nazwa : 'Pokoj_goscinny', nazwa_zm : 'MB_TEMP_11_Pokoj_goscinny', ster_wy : 'wy', rodzaj : 'temp', lok_id : 12},
{rejestr: 'wy_temp', adres: 17219, nazwa : 'Pralnia', nazwa_zm : 'MB_TEMP_12_Pralnia', ster_wy : 'wy', rodzaj : 'temp', lok_id : 15},
{rejestr: 'wy_temp', adres: 17221, nazwa : 'Zewnetrzna', nazwa_zm : 'MB_TEMP_13_Zewnetrzna', ster_wy : 'wy', rodzaj : 'temp', lok_id : 18},
{rejestr: 'wy_temp', adres: 17223, nazwa : 'Wymiennik', nazwa_zm : 'MB_TEMP_14_Wymiennik', ster_wy : 'wy', rodzaj : 'temp', lok_id : 18},
{rejestr: 'wy_temp', adres: 17225, nazwa : 'Nawiew', nazwa_zm : 'MB_TEMP_15_Nawiew', ster_wy : 'wy', rodzaj : 'temp', lok_id : 18},
{rejestr: 'wy_temp', adres: 17227, nazwa : 'Wyciag', nazwa_zm : 'MB_TEMP_16_Wyciag', ster_wy : 'wy', rodzaj : 'temp', lok_id : 18}
]