export const ODCZYT_REJESTRU = 'ODCZYT_REJESTRU'
export const ODCZYT_REGUL = 'ODCZYT_REGUL'

export const ZMIANA_REJESTRU_WYJSCIA = 'ZMIANA_REJESTRU_WYJSCIA'
export const ZMIANA_REJESTRU_WYSATEL = 'ZMIANA_REJESTRU_WYSATEL'
export const ZMIANA_REJESTRU_WYTEMP = 'ZMIANA_REJESTRU_WYTEMP'
export const ZMIANA_REJESTRU_WYTEMPNAST = 'ZMIANA_REJESTRU_WYTEMPNAST'

export const ZMIANA_SWIATLA = 'ZMIANA_SWIATLA'
export const ZMIANA_TEMP = 'ZMIANA_TEMP'
export const ZMIANA_TEMPNAST = 'ZMIANA_TEMPNAST'