export const ODCZYT_REJESTRU: string = 'ODCZYT_REJESTRU';
export const ODCZYT_REGUL: string = 'ODCZYT_REGUL'

export const ZMIANA_REJESTRU_WYJSCIA: string = 'ZMIANA_REJESTRU_WYJSCIA'
export const ZMIANA_REJESTRU_WYSATEL: string = 'ZMIANA_REJESTRU_WYSATEL'
export const ZMIANA_REJESTRU_WYTEMP: string = 'ZMIANA_REJESTRU_WYTEMP'
export const ZMIANA_REJESTRU_WYTEMPNAST: string = 'ZMIANA_REJESTRU_WYTEMPNAST'

export const ZMIANA_SWIATLA: string = 'ZMIANA_SWIATLA'
export const ZMIANA_TEMP: string = 'ZMIANA_TEMP'
export const ZMIANA_TEMPNAST: string = 'ZMIANA_TEMPNAST'